# Generated by Django 2.0.6 on 2018-06-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('birthDay', models.DateField()),
                ('street', models.CharField(max_length=30)),
                ('houseNum', models.IntegerField()),
                ('postCode', models.IntegerField()),
                ('overtime', models.IntegerField()),
                ('leaveDays', models.IntegerField()),
            ],
        ),
    ]
