# Generated by Django 2.0.6 on 2018-06-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_employee_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='birthDay',
            new_name='Geburtstag',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='houseNum',
            new_name='Hausnummer',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='firstName',
            new_name='Nachname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='leaveDays',
            new_name='Postleitzahl',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='city',
            new_name='Stadt',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='Straße',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='street',
            new_name='Vorname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='overtime',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='postCode',
        ),
        migrations.AddField(
            model_name='employee',
            name='Urlaub  ',
            field=models.IntegerField(default='30'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Überstunden',
            field=models.IntegerField(default='0'),
        ),
    ]
