# Generated by Django 2.0.6 on 2018-06-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180624_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Urlaub  ',
            new_name='Urlaub',
        ),
    ]
