# Generated by Django 2.0.6 on 2018-06-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20180624_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='E-Mail',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
