# Generated by Django 2.0.6 on 2018-06-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_employee_e-mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='E-Mail',
        ),
        migrations.AddField(
            model_name='employee',
            name='EMail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
